title: Chidera Ani
logo: chideraani.github.io/assets/img/headshot.png
description: Generative AI engineer and data scientist with 3+ years of experience delivering innovative AI solutions. Proficient in Python, SQL, and cloud platforms (AWS, Azure), with hands-on expertise in building and evaluating generative AI models on cloud. Skilled in evaluating and improving machine- generated outputs, crafting technical solutions, and communicating insights effectively.
show_downloads: true
theme: jekyll-theme-architect
